# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER wyg

# 挂载目录
VOLUME /home/wyg
# 创建目录
RUN mkdir -p /home/wyg
# 指定路径
WORKDIR /home/wyg
# 复制jar文件到路径
COPY ./jar/wyg-visual-monitor.jar /home/wyg/wyg-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","wyg-visual-monitor.jar"]