# 基础镜像
FROM redis
# author
MAINTAINER wyg

# 挂载目录
VOLUME /home/wyg/redis
# 创建目录
RUN mkdir -p /home/wyg/redis
# 指定路径
WORKDIR /home/wyg/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/wyg/redis/redis.conf
